# Generated by Django 4.2.7 on 2024-02-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
