# Generated by Django 4.2.7 on 2024-02-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0002_department_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_table',
            name='discription',
            field=models.CharField(default=0.0004995004995004995, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_table',
            name='qualification',
            field=models.CharField(default=0.0004995004995004995, max_length=50),
            preserve_default=False,
        ),
    ]
