# Generated by Django 4.2.7 on 2024-02-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0003_doctor_table_discription_doctor_table_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_table',
            name='ph_no',
            field=models.IntegerField(default=0.0004995004995004995, max_length=50),
            preserve_default=False,
        ),
    ]
